### ISSUE TITLE
Using git to generate an automatic version number

### ISSUE THREAD

**Issue by newmanix** [gig-central/gig-repo-1#103]
###_MASTER TEMPLATE: Use for bugs, tasks, and future requests. Also, label accordingly, using the labels on the right. 

###_Issue Type - is it a bug, a task, or a future request?:
Future

###_Severity (1-4; 1 - not severe, 4 - very severe):
1
 
###_Priority (1-4; 1 - lowest priority, 4 - highest priority):
1

###_Synopsis - describe bug/task/future request, in more detail:
When people view their existing instance, they may not know if they are working with the version of the code they are expecting.  It appears that developers have used git to generate automated version numbers.  There are several sites that show how they have done this, here is one: 

https://cd34.com/blog/programming/using-git-to-generate-an-automatic-version-number/

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 

###_Actual Behavior - what the behavior is instead, for bugs only: 

###_Steps to Repro the Issue, for bugs only:

###_Other Notes, for bug/task/future requests:

**Comment by Aaron-SCC** [comment]
CLOSING THIS ISSUE SINCE PRIOR QUARTERS WORK AT DATE POINT OF 2019_05_23
