### ISSUE TITLE
Add Venue and Edit Venue / Hours / Needs UI Plugin to Enter Business Hours

### ISSUE THREAD

**Issue by marcusprice** [gig-central/gig-repo-1#120]
The hours input on the add & edit venues pages needs a UI plugin so the business hours that are entered are consistent.

Select on Venues in the Nav Bar
Click on Add Venue
See the text input, it's just a normal input form.

Note: I found this to be a fitting UI for the form, but didn't have time to work out the bugs: https://github.com/gEndelf/jquery.businessHours

###_MASTER TEMPLATE: Use for bugs, tasks, and future requests. Also, label accordingly, using the labels on the right. 

###_Issue Type - is it a bug, a task, or a future request?:
Task

###_Severity (1-4; 1 - not severe, 4 - very severe):
2

###_Priority (1-4; 1 - lowest priority, 4 - highest priority):
2

###_Synopsis - describe bug/task/future request, in more detail: 
The hours input on the add & edit venues pages needs a UI plugin so the business hours that are entered are consistent.

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 
For the user to submit hours via UI plugin so hours entered in the DB are consistent

###_Actual Behavior - what the behavior is instead, for bugs only: 
N/A

###_Steps to Repro the Issue, for bugs only:
N/A

###_Other Notes, for bug/task/future requests: 
N/A

**Comment by Aaron-SCC** [comment]
CLOSING THIS ISSUE SINCE PRIOR QUARTERS WORK AT DATE POINT OF 2019_05_23
