### ISSUE TITLE
Database rebuild

### ISSUE THREAD

**Issue by Shinobu81** [gig-central/gig-repo-1#135]
###_MASTER TEMPLATE: Use for bugs, tasks, and future requests. Also, label accordingly, using the labels on the right. 

###_Issue Type - is it a bug, a task, or a future request?:
task

###_Severity (1-4; 1 - not severe, 4 - very severe):
3
 
###_Priority (1-4; 1 - lowest priority, 4 - highest priority):
3

###_Synopsis - describe bug/task/future request, in more detail: 
Database built in a difficult manner, making hard to access data.

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 
Should be able to pull data on Gigs from a single table.

###_Actual Behavior - what the behavior is instead, for bugs only: 
Currently to pull data on a Gig requires an extensive join method to work.

###_Steps to Repro the Issue, for bugs only:

###_Other Notes, for bug/task/future requests:

**Comment by Aaron-SCC** [comment]
CLOSING THIS ISSUE SINCE PRIOR QUARTERS WORK AT DATE POINT OF 2019_05_23
