### ISSUE TITLE
On Gig Add page, make the Company State field a dropdown

### ISSUE THREAD

**Issue by mikearchie** [gig-central/gig-repo-1#139]
###_MASTER TEMPLATE: Use for bugs, tasks, and future requests. Also, label accordingly, using the labels on the right. 

###_Issue Type - is it a bug, a task, or a future request?:
Task
###_Severity (1-4; 1 - not severe, 4 - very severe):
 1
###_Priority (1-4; 1 - lowest priority, 4 - highest priority):
1
###_Synopsis - describe bug/task/future request, in more detail: 
In views\gigs\add.php: To get the rest of the code working, I had to make the Company State field a text field instead of a dropdown. Changing it back to a dropdown and working on the validation would be a great task for a future class.

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 
User can select State from a dropdown on the Gig Add page, and the site properly validates the field.

###_Actual Behavior - what the behavior is instead, for bugs only: 

###_Steps to Repro the Issue, for bugs only:

###_Other Notes, for bug/task/future requests:

**Comment by thomaskise** [comment]
Closed with pull request #154
