### ISSUE TITLE
Bug: On Gig Add page, the validation for Employment Type is broken

### ISSUE THREAD

**Issue by mikearchie** [gig-central/gig-repo-1#140]
###_MASTER TEMPLATE: Use for bugs, tasks, and future requests. Also, label accordingly, using the labels on the right. 

###_Issue Type - is it a bug, a task, or a future request?:
Bug
###_Severity (1-4; 1 - not severe, 4 - very severe):
 2
###_Priority (1-4; 1 - lowest priority, 4 - highest priority):
2
###_Synopsis - describe bug/task/future request, in more detail: 
On the Gig Add page, if the user doesn't select an Employment Type field, the validation fails and gives a bad error that isn't useful to the user.

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 
If a user doesn't select an Employment Type when adding a new Gig, they are presented with clear information on how to fix the Employment Type field.

###_Actual Behavior - what the behavior is instead, for bugs only: 

###_Steps to Repro the Issue, for bugs only:

###_Other Notes, for bug/task/future requests:

**Comment by thomaskise** [comment]
closed with pull request #152
