### ISSUE TITLE
The date when gig was posted is not accurate

### ISSUE THREAD

**Issue by gminovska** [gig-central/gig-repo-1#16]
Instead of the date when the gig was posted, the current date and time is displayed. To recreate this bug, visit the gig view page twice and see that the date reflects the current system date, not the date the gig was posted.

![image](https://cloud.githubusercontent.com/assets/10931226/26796903/fcf2969e-49df-11e7-9bbd-57a0f0cbc578.png)

**Comment by coultergeist** [comment]
This issue was closed and solved as part of [another issue](https://github.com/gig-central/gig-repo-1/pull/57).
