### ISSUE TITLE
Adding a gig creates a new record in the db, but the new gig does not show up on the gig list.

### ISSUE THREAD

**Issue by craigbpeterson** [gig-central/gig-repo-1#173]
It looks like the Foreign Key "CompanyContactID" is not being entered properly in the "Company" table.

Additionally, the GigPosted" and "LastUpdated" columns of the Gig table are not getting real data.

I am unsure if these are the reasons why the added gig is not showing up on the gigs/index.php view. More research is needed.

**Comment by thomaskise** [comment]
fyi .... I've added gigs. I just added a couple, but I was not logged on.  They all seem to have stuck.  All fields are populated except GigPosted, and LastUpdated is all zeros.

**Comment by esteban-gs** [comment]
IF nobody is working on this issue, I'll assign myself

**Comment by craigbpeterson** [comment]
I think a recent pull request may have resolved this issue. @esteban-gs are you able to add a gig and then see it on the view gigs page?

**Comment by esteban-gs** [comment]
It is writing to the DB, but not showing up on the list:
![image](https://user-images.githubusercontent.com/26440947/58671510-bebb7500-82f7-11e9-9536-38b3f36edbee.png)

**Comment by esteban-gs** [comment]
For me it only shows up when I search for it:
![image](https://user-images.githubusercontent.com/26440947/58671601-13f78680-82f8-11e9-83b0-ed041f91cae4.png)

![image](https://user-images.githubusercontent.com/26440947/58671623-1e198500-82f8-11e9-8402-c3dc1d666bf2.png)

**Comment by esteban-gs** [comment]
I'll assign myself.

**Comment by thomaskise** [comment]
@esteban-gs .... You said above that Gigs are being added.  Did you confirm that the Foreign Key "CompanyContactID" is being set properly in the "Company" table?

If so, I think we should close this one.

**Comment by esteban-gs** [comment]
Yes. It worked on my end

**Comment by thomaskise** [comment]
Closing per PR #233  and above discussion
