### ISSUE TITLE
Make buttons size/weight proportional for pages

### ISSUE THREAD

**Issue by newmanix** [gig-central/gig-repo-1#196]
Buttons
Size/weight proportional for the pages

**Comment by jenevascherr** [comment]
I volunteer for this task if its still available.

**Comment by craigbpeterson** [comment]
@jenevascherr Hey Jeneva-
Jonathan and I volunteered for this story during class yesterday. We are trying to use the "assignees" feature of these issues to claim tasks. Have a look at the list of stories that Thom put together to see what is still available:

https://docs.google.com/document/d/1CfAQUsuZiWzH_L_bDWsA-rHArkBiRNrupFqjyoS9__s/edit#heading=h.8nt4wt4ca2vt

Alternatively, reach out to @james-shively-iii on Slack, he has been working hard to delegate tasks to anyone looking for the next step.

**Comment by craigbpeterson** [comment]
The button styles have been standardized. Let's go!
