### ISSUE TITLE
Remove Non MVP Features from navigation

### ISSUE THREAD

**Issue by michaelrodgers** [gig-central/gig-repo-1#198]
###_Issue Type - is it a bug, a task, or a future request?: 
"Mothball-ing" feature

###_Severity (1-4; 1 - not severe, 4 - very severe): 
1
 
###_Priority (1-4; 1 - lowest priority, 4 - highest priority): 
4

###_Synopsis - describe bug/task/future request, in more detail: 
Hide non-MVP features from the site.

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 
Features should still be available for future work, but removed from public view.
Refer to **MVP spec:** https://docs.google.com/document/d/1CfAQUsuZiWzH_L_bDWsA-rHArkBiRNrupFqjyoS9__s/edit#heading=h.6pxvwjg22s62

###_Other Notes, for bug/task/future requests: 
See Milestone Non MVP Features

**Comment by thomaskise** [comment]
I think this should be closed!

**Comment by thomaskise** [comment]
Fixed with #217 and #220
