### ISSUE TITLE
Labeling and styling of form fields

### ISSUE THREAD

**Issue by craigbpeterson** [gig-central/gig-repo-1#200]
Update form labels so that they aren't so redundant. Example: the labels for the add gig form all include the word "gig" which isn't really necessary. The styling of these labels and input fields should be standardized and the styling documented so that it can be applied to all forms moving forward (such as the add profile and add venue forms, which will be implemented AFTER the MVP has been finished).

**Comment by TheBaldWonder** [comment]
My pull request: **https://github.com/gig-central/gig-repo-1/pull/216** completes this issue

**Comment by thomaskise** [comment]
Can't find the pull request for this, and a physical examination shows the work has been done.

Closing.
