### ISSUE TITLE
"Gig Detail" page should require authentication

### ISSUE THREAD

**Issue by andylwilson** [gig-central/gig-repo-1#203]
**###_Issue Type - is it a bug, a task, or a future request?:**
Task
**###_Severity (1-4; 1 - not severe, 4 - very severe):**
4
**###_Priority (1-4; 1 - lowest priority, 4 - highest priority):**
4
**###_Synopsis - describe bug/task/future request, in more detail:** 
The gig details page must be unavailable unless user is logged in, as it displays the Employer's sensitive contact information. The "Apply" button should be removed from the details page as this functionality is not yet developed.
![image](https://user-images.githubusercontent.com/26440947/58669794-fde6c780-82f1-11e9-9210-2f746436d4e4.png)

**###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR:** 
Details page should only be available when user is logged in, and "Apply" button should be removed.
Refer to MVP spec: https://docs.google.com/document/d/1CfAQUsuZiWzH_L_bDWsA-rHArkBiRNrupFqjyoS9__s/edit#heading=h.6pxvwjg22s62
**###_Actual Behavior - what the behavior is instead, for bugs only:** 
Currently anyone viewing the site can access gig details, which displays Employer contact info.

**###_Steps to Repro the Issue, for bugs only:**
Gigs/find a gig/Read More
**###_Other Notes, for bug/task/future requests:** 
N/A

**Comment by esteban-gs** [comment]
Authentication works. However the session with user data is not persisting.  So, sessions might have to become a separate issue. 

Once the Session handling is debugged, the Admin navigation should display. The logic for toggling the admin navigation/ non-admin navigation is in application/libraires/Navigation.php:

These are the lines that handle the toggling:
`        if ($codeIgniter->session->logged_in == TRUE)
        {
            $editProfile = array(
                'text'		     => 	'Edit Profile',
                'link'		     => 	base_url() . 'profiles/edit',
                'show_condition' =>	    1,
                'parent'	     => 	8
            );

            $editVenues = array(
                'text'		     => 	'Edit Venues',
                'link'		     => 	base_url() . 'venues/edit',
                'show_condition' =>	    1,
                'parent'	     =>	    5
            );
            
            $editGig = array(
                'text'		     => 	'Edit Gig',
                'link'		     => 	base_url() . 'gig/edit',
                //'Edit' menu is hidden
                'show_condition' =>	    0,
                'parent'	     =>	    2
            );
            
            //If user id matches id stored in a post, 
            //change the value in 'show_condition' for $editGig to show 'Edit' menu
            if($gigResult == true)
            {
                $editGig['show_condition'] = 1;
            } 

            $login = array(
                    'text'		    => 	'Logout',
                    'link'		    => 	base_url() . 'admin/logout',
                    'show_condition'=>	1,
                    'parent'	    =>	0
                );

            //adding $login to show the user loggin status
            array_push($headerNavigation,$editProfile,$editVenues,$editGig,$login);

        } `
Also 
![20190531_041028](https://user-images.githubusercontent.com/26440947/58702309-4cc84780-835a-11e9-80b3-fc7cabe85a3e.gif)

**Comment by esteban-gs** [comment]
Aslo, sessions is working for some:
http://kelsiebrown.com/gig-central/contact
![image](https://user-images.githubusercontent.com/26440947/58703684-4936bf80-835e-11e9-8174-53389d73bc4a.png)
