### ISSUE TITLE
Updating "Find a Gig" page for authentication

### ISSUE THREAD

**Issue by andylwilson** [gig-central/gig-repo-1#204]
### Issue Type - is it a bug, a task, or a future request?:
Task
### Severity (1-4; 1 - not severe, 4 - very severe):
4
### Priority (1-4; 1 - lowest priority, 4 - highest priority):
4
###_Synopsis - describe bug/task/future request, in more detail: 
"Find a Gig" page needs to be updated for authentication, so that users should see a "click for more" link under each gig only when a user is logged in, as the details page contains the employer's sensitive contact information. The gigs list page should display no contact information, but should show fields for:
Type of job
Location
Duration
Language
A prompt for login to view more
Only show gigs that have not expired (on or before “Gig close date”)

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 
The "Find a Gig" page should display a list of gigs with the details noted, and when not logged in should have some sort of prompt (text or button) to urge the user to log in to see view more. When logged in, that prompt should instead be a "click for more" link that goes to the Gig Detail page to display the employer's contact info.

***** See Jeneva's & Thom's comments below.  Here's a use case for this:

User selects Gig List page
 - System presents page with list with Gig items that link to details
User selects a Gig item
 -  System takes user to login page
User logs in
 - System takes user to Gig Details page

###_Actual Behavior - what the behavior is instead, for bugs only: 
Currently anyone viewing the site can access gig details, which displays Employer contact info.

###_Steps to Repro the Issue, for bugs only:
N/A
###_Other Notes, for bug/task/future requests: 
N/A

#### Gig list

- **Remove company name**
- **Put “job title”  in place of company name**
- **Add description**
- **Add icons/images**
- **Is it possible to find icons/images that match the job title?** (e.g., Python, Java, PHP, etc logos)

**Comment by jenevascherr** [comment]
Rather than Prompt the user to log on as soon as the page opens, How about giving each gig an on-click function that will either redirect the user to the login page or create a pop-up for the log in page?

**Comment by thomaskise** [comment]
Jeneva - you are absolutely on the right track with this ... the link to details should always show on the list item (just make the list item a link) and then if the user is not logged in, they are redirected to login.

it would be good to have an alert something to the effect of "You must be logged in to see Gig Details"

**Comment by james-shively-iii** [comment]
I think this can be broke down into more than just one task.

**Comment by thomaskise** [comment]
James .... what is your suggestion or breaking this down?

**Comment by esteban-gs** [comment]
This issue is fixed with this commit: #217. 
![20190604_091705](https://user-images.githubusercontent.com/26440947/58895857-ba051100-86a9-11e9-9a51-ad3206944629.gif)

**Comment by thomaskise** [comment]
@esteban-gs .... pull #228 fixed this. Correct?

**Comment by esteban-gs** [comment]
Yes. Read more, now prompts user to log in

**Comment by thomaskise** [comment]
Closing this item per fix in pull#228 and above conversation.
