### ISSUE TITLE
Find a gig page list needs to check for expired gigs

### ISSUE THREAD

**Issue by jenevascherr** [gig-central/gig-repo-1#210]
###_MASTER TEMPLATE: Use for bugs, tasks, and future requests. Also, label accordingly, using the labels on the right. 
#210
###_Issue Type - is it a bug, a task, or a future request?:
Task
###_Severity (1-4; 1 - not severe, 4 - very severe):
 2
###_Priority (1-4; 1 - lowest priority, 4 - highest priority):
3
###_Synopsis - describe bug/task/future request, in more detail: 
The list of gigs in the Find a Gig page needs to be able to update itself by checking the expiration date of each of its items ($GigCloseDate) and stop displaying any unavailable or expired gigs.

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 
Every time the page is opened or refreshes, Gigs that are past their Close date are not longer shown and new ones are added.

###_Actual Behavior - what the behavior is instead, for bugs only: 

###_Steps to Repro the Issue, for bugs only:

###_Other Notes, for bug/task/future requests:

**Comment by thomaskise** [comment]
Seems to be fixed - closing
