### ISSUE TITLE
Fix gig add validation

### ISSUE THREAD

**Issue by thomaskise** [gig-central/gig-repo-1#224]
### Newly added detail
The state dropdown error message is symptomatic of a larger problem with validation.  This issue is being detailed to address the larger problem

- [x] - Main validation code resides in application/config/form_validation.php, not the controller
### Validation should not be overly restrictive
- [x] - Check to see if standard validations are available - should be for things like zip, phone, email address, website
- [x] - Date format - use calendar select? How is it read now? KISS (Tran, issue #209) (createing seperate task for tis)
- [x] - Name/Address/City/Description/Qualifications/Special instructions should be pretty wide open - alpha/numeric/special char
- [x] - Dropdowns should not need validation except they need to be selected - we should assume that we haven’t offered any invalid selections
### Original entry below
**********************************************************************************************************
###_MASTER TEMPLATE: Use for bugs, tasks, and future requests. Also, label accordingly, using the labels on the right. 

###_Issue Type - is it a bug, a task, or a future request?:
Bug
###_Severity (1-4; 1 - not severe, 4 - very severe):
 1
###_Priority (1-4; 1 - lowest priority, 4 - highest priority):
1
###_Synopsis - describe bug/task/future request, in more detail: 
If a selection is not made error message says "The CompanyState field may only contain alphabetical characters."

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 

Error message should say "The CompanyState must be selected.."

###_Actual Behavior - what the behavior is instead, for bugs only: 
If a selection is not made error message says "The CompanyState field may only contain alphabetical characters."

###_Steps to Repro the Issue, for bugs only:
Go to Post a Gig page
press add without selecting a state

###_Other Notes, for bug/task/future requests: 

This is a custom message. Issue #140 had previously captured another error with state error handling and was  fixed.  I think at least part of the problem comes from adding rules to  the Gig controller. They are also handled in application/config/form_validation.php, and I think this is the correct place for them.

See [this writeup for more information](https://docs.google.com/document/d/1yOdaz814XkteHxVWo5T7Op-V99hGcSi2Qimz78nssRw/edit#). 

[CI Validation documentation](https://www.codeigniter.com/user_guide/libraries/form_validation.html#saving-sets-of-validation-rules-to-a-config-file)

**Comment by tranzilla** [comment]
@andylwilson I am going to take a look at this and see what I can do. I am also working on the google map so if you find any free time to help, that would be great!

**Comment by thomaskise** [comment]
@andylwilson , @tranzilla ....
The problem with the one error message is really a symptom, of a larger issue. I think we should repurpose this task and expand it to fixing the validation. I'm going to change the title and add detail above

@andylwilson Since Tran is focusing on Maps, I can help you out with this if you need.

**Comment by esteban-gs** [comment]
@thomaskise  and @tranzilla the state dropdown validation is fixed with pull request #237

**Comment by esteban-gs** [comment]
More on how this was fixed:
...validation should be set in the form_validation.php file in the config folder. The cause this issue is that there was a set of validation rules in form_validation.php as well as in the gig/add method. 

https://github.com/gig-central/gig-repo-1/pull/237/files#r291823475

**Comment by thomaskise** [comment]
Closing issue
