### ISSUE TITLE
Homepage Design

### ISSUE THREAD

**Issue by james-shively-iii** [gig-central/gig-repo-1#229]
#### **Description of what Gig Central is**
- Some info on the page
- Additional info may be accessible via a link
#### **Find a Gig functionality**
- Dashboard
- Map
- Short list of jobs
#### **Post a Gig functionality**
- Not on the page - but need a link and maybe some info under “What Gig Central is”

**WORK:**
- Design maximum 3 prototype concepts for homepage that are clear and concise
- Add a link to _Learn More_ to page that user can learn more about Gig Central
- Add images to spruce up the design
- Make it more interesting
- Break up the text
- Make it more readable/consumable
- Add icons/small images next to title and other headings & on the filters
- Consider randomizing (Bill has a randomize plugin)
- Fontawesome icons or the filters
- Consider different business theme icons/images
- Add map _(Tran has done most of this work to implement this into this)_

> Some of these are suggestions are not expected to be 100% finished by the end of this quarter given we have 4 days (from the date of this task creation)

**Comment by thomaskise** [comment]
Design complete see: https://docs.google.com/document/d/1y09QSJhGZjgrfmB9UHVfSygPkOAkQQmrvlUQiCdCKWY/edit
and
https://docs.google.com/document/d/1Nuna4NE2Li0_wLXXv-Ytthjrt8LKcd8i9LphggceQpU/edit

Adding story to update home page
