### ISSUE TITLE
CSS changes **already done**

### ISSUE THREAD

**Issue by james-shively-iii** [gig-central/gig-repo-1#235]
### Find out what the standard for the page heading is and use it
(what’s there could be the standard, but the site is not consistent)

**WORK:**
_This is already done by Jeneva but the task was never created for the backlog_

**Comment by thomaskise** [comment]
Heads are not consistent, so I think there is still work to be done on this:
![image](https://user-images.githubusercontent.com/43864992/59156989-9864aa80-8a58-11e9-9621-a9116d9c80bf.png)

![image](https://user-images.githubusercontent.com/43864992/59156994-afa39800-8a58-11e9-92ef-b3bf6778ae00.png)

**Comment by thomaskise** [comment]
This isn't already done as the title says, but it is probably better worked in the context of other changes - and it is not critical. Closing this issue.
