### ISSUE TITLE
Error thrown by "employment type" dropdown when submitting a valid gig/add form

### ISSUE THREAD

**Issue by josephwanderer** [gig-central/gig-repo-1#26]
###_MASTER TEMPLATE: Use for bugs, tasks, and future requests. Also, label accordingly, using the labels on the right. 

###_Issue Type - is it a bug, a task, or a future request?:
Bug
###_Severity (1-4; 1 - not severe, 4 - very severe):
 2
###_Priority (1-4; 1 - lowest priority, 4 - highest priority):
2
###_Synopsis - describe bug/task/future request, in more detail: 

The "employment type" dropdown field in the gig/add form throws an error on submit.

This is caused by a naming mismatch. In the add() method of the gig controller (line 78) there is a function call that takes another function name as the first parameter, which is 'check_dropdown' in this case:
$this->form_validation->set_message('check_dropdown', 'You need to select an employment type.');
But on line 68 in form_validation.php in the config folder the validation rule uses a different name for the function:
'rules' => 'required|callback_checkDropdown'

These names need to be brought into accord under PSR1 standards wherever they appear.

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 

The "Employment Type" Form data should be posted and inserted into the database

###_Actual Behavior - what the behavior is instead, for bugs only: 

An error message appears that mentions that an error message for checkDropdown() can't be set.

###_Steps to Repro the Issue, for bugs only:

In the gig/add form click submit with all fields filled validly

###_Other Notes, for bug/task/future requests:

**Comment by amybartolotta** [comment]
https://github.com/gig-central/gig-repo-1/pull/52
https://github.com/gig-central/gig-repo-1/pull/54
