### ISSUE TITLE
Venues/add form throws error when nothing's selected for the Venue Type dropdown

### ISSUE THREAD

**Issue by josephwanderer** [gig-central/gig-repo-1#29]
###_MASTER TEMPLATE: Use for bugs, tasks, and future requests. Also, label accordingly, using the labels on the right. 

###_Issue Type - is it a bug, a task, or a future request?:
bug
###_Severity (1-4; 1 - not severe, 4 - very severe):
 2
###_Priority (1-4; 1 - lowest priority, 4 - highest priority):
2
###_Synopsis - describe bug/task/future request, in more detail: 
A Database Error Occurred
Error Number: 1452
Cannot add or update a child row: a foreign key constraint fails (`education_sandbox_db`.`Venue`, CONSTRAINT `Venue_ibfk_1` FOREIGN KEY (`VenueTypeKey`) REFERENCES `VenueType` (`VenueTypeKey`) ON DELETE CASCADE)

INSERT INTO `Venue` (`VenueName`, `VenueTypeKey`, `VenueAddress`, `City`, `State`, `ZipCode`, `VenuePhone`, `VenueWebsite`, `VenueHours`, `Food`, `Bar`, `Outlets`, `WiFi`, `Outdoor`, `Wheelchair`, `Parking`) VALUES ('f', 'select', 'f', 'f', 'f', 'f', 'f', '', '', 'No', 'No', 'No', 'No', 'No', 'No', 'No')

Filename: models/Venues_model.php
Line Number: 116

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 

Form Validation rules should return me to the form with a prompt to select a Venue Type from the dropdown or nothing being selected from the dropdown should be accepted as valid input

###_Actual Behavior - what the behavior is instead, for bugs only: 

The above error message is thrown

###_Steps to Repro the Issue, for bugs only:
Step 1: Go to venues/add
Step 2: Leave the Venue Type dropdown input untouched but fill out all other required fields with valid input.
Step 3: Click Submit

###_Other Notes, for bug/task/future requests:

**Comment by MariamAbdelmohsen** [comment]
https://github.com/gig-central/gig-repo-1/tree/bug-venues-add
