### ISSUE TITLE
Gigs/add form throws error for the Employment Type dropdown for everything that is selected

### ISSUE THREAD

**Issue by James0831** [gig-central/gig-repo-1#49]
###_MASTER TEMPLATE: Use for bugs, tasks, and future requests. Also, label accordingly, using the labels on the right. 

###_Issue Type - is it a bug, a task, or a future request?:
bug
###_Severity (1-4; 1 - not severe, 4 - very severe):
 4
###_Priority (1-4; 1 - lowest priority, 4 - highest priority):
3
###_Synopsis - describe bug/task/future request, in more detail: 
When you select an Employment Type from the dropdown it displays the following error
 "_Unable to access an error message corresponding to your field name Employment type.(checkDropdown)_"

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 

It should allow the user to select one of the Employment Type options from the dropdown and be inserted into the database

###_Actual Behavior - what the behavior is instead, for bugs only: 

The above error is thrown

###_Steps to Repro the Issue, for bugs only:

Step 1: Go to gigs/post
Step 2: Select the Employment Type dropdown input and fill out all other required fields with valid input.
Step 3: Click Submit

###_Other Notes, for bug/task/future requests:

**Comment by amybartolotta** [comment]
https://github.com/gig-central/gig-repo-1/pull/52
https://github.com/gig-central/gig-repo-1/pull/54
