### ISSUE TITLE
Issue with mobile display

### ISSUE THREAD

**Issue by Ariton84** [gig-central/gig-repo-1#60]
###_MASTER TEMPLATE: Use for bugs, tasks, and future requests. Also, label accordingly, using the labels on the right. 

###_Issue Type - is it a bug, a task, or a future request?:
          A bug 
###_Severity (1-4; 1 - not severe, 4 - very severe):
          2
###_Priority (1-4; 1 - lowest priority, 4 - highest priority):
          3
###_Synopsis - describe bug/task/future request, in more detail: 
          Text is not aligned with boxes in mobile view

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 
          Text should be aligned in the boxes when viewing site from mobile

###_Actual Behavior - what the behavior is instead, for bugs only: 
           Text is aligned along the bottom of the boxes and trailing out the bottom.

###_Steps to Repro the Issue, for bugs only:
           Likely issue is in the css on how the text is aligned in media view sized on a mobile phones.

###_Other Notes, for bug/task/future requests:

**Comment by fncreative** [comment]
This has been corrected. I've changed the bar to not appear with any resolution less than 768px, as well as changed the behavior of the h1,h3, and p tags on the smaller mobile views.
