### ISSUE TITLE
Issue with breadcrumb sub navigation

### ISSUE THREAD

**Issue by nbrownseattle** [gig-central/gig-repo-1#62]
###_MASTER TEMPLATE: Use for bugs, tasks, and future requests. Also, label accordingly, using the labels on the right. 

###_Issue Type - is it a bug, a task, or a future request?:
A bug

###_Severity (1-4; 1 - not severe, 4 - very severe):
Sev 2 - not severe  as users can still use the main navigation to browse back to desired page.

###_Priority (1-4; 1 - lowest priority, 4 - highest priority):
3

###_Synopsis - describe bug/task/future request, in more detail: 
Breadcrumb navigation is not working on the following two pages:
Gig Read More (details) page & View Venue Details page.

###_Actual Behavior - what the behavior is instead, for bugs only: 
Breadcrumb navigation does nothing when user clicks on the breadcrumb nav links.

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 
User should be able to use the breadcrumb navigation to browse back to previous page or home.

###_Steps to Repro the Issue, for bugs only:
1. user selects Gigs/Find a Gig from the main navigation drop down menu.
2. from the gigs page user clicks Read More link for the company Amazon
3. from Amazon gig details page user clicks on the Gigs link on breadcrumb navigation. Nothing happens.  Same behavior with Home breadcrumb. 

1. user selects Venues/Find a Venue  from the main navigation drop down menu.
2. from the Venues page user clicks View Venue Details link.
3. From the venue details page user clicks on the Venues link on the breadcrumb navigation. Nothing happens. Sane behavior with Home breadcrumb.

###_Other Notes, for bug/task/future requests:

**Comment by Ariton84** [comment]
Issue fix has been tested and merged with master.
