### ISSUE TITLE
Add a new gig bug

### ISSUE THREAD

**Issue by danieldouglas88** [gig-central/gig-repo-1#64]
###_MASTER TEMPLATE: Use for bugs, tasks, and future requests. Also, label accordingly, using the labels on the right. 

###_Issue Type - is it a bug, a task, or a future request?:
a bug,

###_Severity (1-4; 1 - not severe, 4 - very severe):
3. Severe because people can't submit a new gig without a fix.

###_Priority (1-4; 1 - lowest priority, 4 - highest priority):
3. It should be one of the first bugs to be fixed.

###_Synopsis - describe bug/task/future request, in more detail: 
When trying to add a new gig, the following bug arises which results in the user not being able to submit the form: "Unable to access an error message corresponding to your field name Employment type.(checkDropdown)"

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 
Form is suppose to be successfully submitted without errors or bugs arising.

###_Actual Behavior - what the behavior is instead, for bugs only: 
Error message is popping up: "Unable to access an error message corresponding to your field name Employment type.(checkDropdown)"

###_Steps to Repro the Issue, for bugs only:
Go to Gigs > Post a gig, then fill out the form and try to submit it. Then the error will pop up after attempted form submission.

###_Other Notes, for bug/task/future requests:

**Comment by Ariton84** [comment]
This issue has been fixed and merged to the master branch.
