### ISSUE TITLE
Gig Central documentation - some docs are read only

### ISSUE THREAD

**Issue by nbrownseattle** [gig-central/gig-repo-1#69]
###_MASTER TEMPLATE: Use for bugs, tasks, and future requests. Also, label accordingly, using the labels on the right. 

###_Issue Type - is it a bug, a task, or a future request?:
Bug

###_Severity (1-4; 1 - not severe, 4 - very severe):
 Sev 1 - not customer facing.

###_Priority (1-4; 1 - lowest priority, 4 - highest priority):
Priority 1

###_Synopsis - describe bug/task/future request, in more detail: 
The following docs are read only. Teams will not be able to update these over time.
Github Example Workflow 
GitHub Standards

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 
Docs should be editable by all or ownership transferred to instructor (who can grant permissions as needed).
###_Actual Behavior - what the behavior is instead, for bugs only: 
No one in our class has permissions to edit these two documents. They may be owned by former students.

###_Steps to Repro the Issue, for bugs only:
1. Log in to Canvas
2. See Module 5: Gig Central Staging Are
3. Try these these links:
https://docs.google.com/document/d/1X9cXI-d4VJrD4T_nErQmxl6qBIKHLaAYKnfrYUbCByM/edit?usp=sharing

https://docs.google.com/document/d/1R4JuDA_iQ0LYVLjzLzzNo-sY2FUXVXpWYUunRhaQ-mY/edit?usp=sharing

4. Mode shows as View only.  

###_Other Notes, for bug/task/future requests: 
Document authors are:
Adam Kozie/Deklan Alasdy

**Comment by Idanord** [comment]
These have been set to anyone with the link.
