### ISSUE TITLE
Git Tracking config files with sensitive information

### ISSUE THREAD

**Issue by gillilands19** [gig-central/gig-repo-1#74]
###_MASTER TEMPLATE: Use for bugs, tasks, and future requests. Also, label accordingly, using the labels on the right. 

###_Issue Type - is it a bug, a task, or a future request?:
Task

###_Severity (1-4; 1 - not severe, 4 - very severe):
2, depends on who else is running local servers on their development machines
 
###_Priority (1-4; 1 - lowest priority, 4 - highest priority):

1

###_Synopsis - describe bug/task/future request, in more detail: 

git is tracking all files in "application/config" including the database.php file with credentials and the custom_config.php file which has custom api keys for google services. This poses a security risk for those who are currently and in the future developing with local servers such as MAMP, XAMMP, WAMP, or any other LAMP stack development environment.

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 

The entire Application/config folder should be in the .gitignore file so git no longer tracks files with sensitive information

###_Actual Behavior - what the behavior is instead, for bugs only: 

Git is tracking config files with sensitive information

###_Steps to Repro the Issue, for bugs only:

add application/config to .gitignore

###_Other Notes, for bug/task/future requests:

**Comment by Ariton84** [comment]
I'm also going to add the config.php file to .gitignore.
