### ISSUE TITLE
Welcome Logout Message

### ISSUE THREAD

**Issue by pianohagens** [gig-central/gig-repo-1#76]
##### Issue Type - is it a bug, a task, or a future request?:
A future request
##### Severity (1-4; 1 - not severe, 4 - very severe):
 1
##### Priority (1-4; 1 - lowest priority, 4 - highest priority):
2
##### Synopsis - describe bug/task/future request, in more detail: 
This is logout message: **Welcome-Login to see your person.-Logout**
It shoud be a better sentence like "You have logged out GigCentral"

**Comment by Idanord** [comment]
This would be a good idea to have a better sentance than what it says currently.
