### ISSUE TITLE
Doesn't Pick up entry of Venue Expiration Date

### ISSUE THREAD

**Issue by pianohagens** [gig-central/gig-repo-1#78]
### Issue Type - is it a bug, a task, or a future request?:
a task
### _Severity (1-4; 1 - not severe, 4 - very severe):
2
### Priority (1-4; 1 - lowest priority, 4 - highest priority):
4
### Synopsis - describe bug/task/future request, in more detail: 
This is what the app show for Venue Expiration Date: 0000-00-00 00:00:00, when a Venue Expiration Date entered.
### Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 
Pick up entry. It would be nicer if using a drop down calendar instead entering a date format.
### Actual Behavior - what the behavior is instead, for bugs only: 
Using a drop down calendar instead
### Other Notes, for bug/task/future requests:

**Comment by Idanord** [comment]
This would be more of an enhancement than a bug. The experation date does show up when you go into further details on the gigs list (read more link). Though to enhance this would be good if we were able to have the closing date on the list page as well as the view page.
