### ISSUE TITLE
Can't add More Then One Venue Post 

### ISSUE THREAD

**Issue by pianohagens** [gig-central/gig-repo-1#79]
#### Issue Type - is it a bug, a task, or a future request?:
a bug
#### Severity (1-4; 1 - not severe, 4 - very severe):
 4
#### Priority (1-4; 1 - lowest priority, 4 - highest priority):
3
#### Synopsis - describe bug/task/future request, in more detail: 
The app only take one Venue post, which is can't Add more than 1 Venue. The 2nd new entry doesn't go to database either.
#### _Expected Behavior - what the behavior is supposed to be, for bug/task/FR:
Should store as much post as entry, but limit amount of posts, and provide a "See More Venue" button to track post records.
#### Actual Behavior - what the behavior is instead, for bugs only: 
Can't add More Then One Venue Post 
#### Other Notes, for bug/task/future requests:

**Comment by Ariton84** [comment]
Can't duplicate error, can post multiple venues with the most recent build from master branch
