### ISSUE TITLE
Can't edit post->404 Page Not Found

### ISSUE THREAD

**Issue by pianohagens** [gig-central/gig-repo-1#80]
#### Issue Type - is it a bug, a task, or a future request?:
A bug
#### Severity (1-4; 1 - not severe, 4 - very severe):
 4
#### Priority (1-4; 1 - lowest priority, 4 - highest priority):
4
#### Synopsis - describe bug/task/future request, in more detail: 
Can't edit Venues, it goes to 404 Page Not Found
#### Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 
Should be able to re-edit any post of posted
#### Actual Behavior - what the behavior is instead, for bugs only: 
edit page is missing
#### Other Notes, for bug/task/future requests:

**Comment by Idanord** [comment]
can you please describe this further?

**Comment by Idanord** [comment]
Vanver and I will look into this issue.

**Comment by pianohagens** [comment]
Great, Thank you!

**Comment by Idanord** [comment]
No problem

**Comment by Idanord** [comment]
Looks like this never got built

**Comment by Ariton84** [comment]
This was fixed in the previous quarter
