### ISSUE TITLE
Post Gig Error - > Employment Type

### ISSUE THREAD

**Issue by pianohagens** [gig-central/gig-repo-1#81]
#### Issue Type - is it a bug, a task, or a future request?:
A bug
#### Severity (1-4; 1 - not severe, 4 - very severe):
 4
#### Priority (1-4; 1 - lowest priority, 4 - highest priority):
4
#### Synopsis - describe bug/task/future request, in more detail: 
Employment Type has dropdown options to select a type, but everyone of them selected, show message of  **Unable to access an error message corresponding to your field name Employment type.(checkDropdown)** . It also cost unable to submit
#### Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 
Should be able to select any employment type from dropdown

#### Actual Behavior - what the behavior is instead, for bugs only: 
Post Gig Error - > Employment Type

#### Other Notes, for bug/task/future requests:

**Comment by Ariton84** [comment]
fixed

**Comment by pianohagens** [comment]
Tested, Works Great! Thumb Up
