### ISSUE TITLE
Can't add a Gig | DB Error - Column ID cannot be NULL

### ISSUE THREAD

**Issue by gillilands19** [gig-central/gig-repo-1#82]
###_MASTER TEMPLATE: Use for bugs, tasks, and future requests. Also, label accordingly, using the labels on the right. 

###_Issue Type - is it a bug, a task, or a future request?:
Bug

###_Severity (1-4; 1 - not severe, 4 - very severe):
 4

###_Priority (1-4; 1 - lowest priority, 4 - highest priority):
4

###_Synopsis - describe bug/task/future request, in more detail: 

When all fields are filled out and form is submitted a Database error occurs. 'Column  "id" cannot be NULL'.

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 

Form should submit successfully and the new gig should be added to the database.

###_Actual Behavior - what the behavior is instead, for bugs only: 

Database Error Occurs. 

###_Steps to Repro the Issue, for bugs only:

Column "id" refers to the userID of the person who submitted the gig form which is currently being attempted to be retrieved by the current session_ID value. Line 117 in Gig_model.php returns NULL. We should check to make sure that a session is started on login. However my understanding is that even non logged in users should be able to submit a gig. We either need to do a check that says 'if session_ID exists, use that id for column 'ID'. Else is session_id doesn't exist auto generate a random id.

We could also make the column 'id'  NULLABLE in the database, so that if a non logged in user adds a gig, the id value can be NULL

###_Other Notes, for bug/task/future requests:

**Comment by danieldouglas88** [comment]
Corresponding issue --> https://github.com/gig-central/gig-repo-1/pull/70

**Comment by Ariton84** [comment]
Fixed
