### ISSUE TITLE
Search for Gig Bug

### ISSUE THREAD

**Issue by myra090989** [gig-central/gig-repo-1#83]
###_MASTER TEMPLATE: Use for bugs, tasks, and future requests. Also, label accordingly, using the labels on the right. 

###_Issue Type - is it a bug, a task, or a future request?:
A bug.

###_Severity (1-4; 1 - not severe, 4 - very severe):
3 - Pretty severe: User is not able to search for a gig.

###_Priority (1-4; 1 - lowest priority, 4 - highest priority):
3 - Big priority, but many users may not use this particular functionality.

###_Synopsis - describe bug/task/future request, in more detail: 
User cannot search for a gig when they submit a search form.

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 
You're supposed to be able to search for a gig successfully.

###_Actual Behavior - what the behavior is instead, for bugs only: 
Fails to find anything went search form is submitted.

###_Steps to Repro the Issue, for bugs only:
Go to /gig-central/gig and try to search for a preexisting gig.

###_Other Notes, for bug/task/future requests:

**Comment by Idanord** [comment]
Cannot duplicate. Search function is working for both Vanver and I.

**Comment by Ariton84** [comment]
The search Function works in my most recent build from the master branch, if you can test it on your machines with the most recent build let me know
