### ISSUE TITLE
Can't reset password - Bug

### ISSUE THREAD

**Issue by danieldouglas88** [gig-central/gig-repo-1#92]
###_MASTER TEMPLATE: Use for bugs, tasks, and future requests. Also, label accordingly, using the labels on the right. 

###_Issue Type - is it a bug, a task, or a future request?:
Bug.

###_Severity (1-4; 1 - not severe, 4 - very severe):
 4 - If user forgets password, they cannot reset it.

###_Priority (1-4; 1 - lowest priority, 4 - highest priority):
4.

###_Synopsis - describe bug/task/future request, in more detail: 
When you submit the form, it doesn't reset the password or do anything other than show a random string on the screen. 

###_Expected Behavior - what the behavior is supposed to be, for bug/task/FR: 
It's supposed to write to the DB the new password, as well as send email to user with new PW.

###_Actual Behavior - what the behavior is instead, for bugs only: 
Goes to blank screen with random string.

###_Steps to Repro the Issue, for bugs only:
Login -> Forgot Password -> Reset my Password

###_Other Notes, for bug/task/future requests:

**Comment by Idanord** [comment]
This bug is being worked on by Michael G with the password reset link task
